# -*- coding: utf-8 -*-
"""MailSending

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qxtmv3C6STuhnHmVY4bgEoxhNyqF4MFB
"""

# Email sending prog
import smtplib
import ssl
from email.mime.text import MIMEText as MT
from email.mime.multipart import MIMEMultipart as MM

# Store the email adresses for the receiver and the sender and store the senders password
reciever = input('Reciever email:  ')
sender = input('Sender email:  ')
senders_password = input("Sender's email: ")

# Create a MIMEMultipart object
msg = MM()
subject = input('input email subject: ')
msg['Subject'] = subject
msg['From'] = reciever
msg['To'] = sender

HTML = """
<html>
  <body>  
    <h1>LOKTAR A ANAL!</h1>
    <img src="https://cs10.pikabu.ru/post_img/big/2019/10/04/4/157016829313763586.png" alt="ebany bezdelnik" width="500" height="600">
    <h2>
    <p>Go to RABOTA<br>
    Your future in Ogrrimar: <a href = "https://sun9-69.userapi.com/impg/kBeMPri1JwlEqyIf4GqEC7lciCYx0R-DqmehMQ/yadRp3B6H1g.jpg?size=607x794&quality=96&sign=6fca02fa3f8707c002dcc3db75e26e66&type=album"> Join US</a>
    </p>
    </h2>
  </body>
</html>
"""

# Create a html MIMEText  object
MTObj = MT(HTML, "html")

# Attach the MIMEtext object into the message container
msg.attach(MTObj)

# Create a "secure" connection with teh server and send email
# Create the secure socket layer (SSL) context obj
SSL_context = ssl.create_default_context()
# Create the secute simple mail transfer protcol (SMTP) connection
server = smtplib.SMTP_SSL(host = 'smtp.gmail.com', port = 465, context = SSL_context)
# Login
server.login(sender,senders_password)
# Send the email
server.sendmail(sender, reciever, msg.as_string())